nestolovaya_itmo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import re_path, include

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^', include('recSys.urls')),
    re_path(r'^reservation/', include('reservation.urls')),
    re_path(r'', include('social_django.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recSys/urls.py
from django.urls import re_path

from recSys import views

urlpatterns = [
    re_path(r'^menu/detail/(?P<menu_id>\d+)/$', views.menu_detail, name='menu_detail'),
    re_path(r'^menu/update/(?P<menu_id>\d+)/$', views.menu_update, name='menu_update'),
    re_path(r'^menu/delete/(?P<menu_id>\d+)/$', views.menu_delete, name='menu_delete'),
    re_path(r'^menu/food-type/$', views.food_type, name='food_type'),
    re_path(r'^menu/food-type/update/(?P<food_type_id>\d+)/$', views.food_type_update, name='food_type_update'),
    re_path(r'^menu/food-type/delete/(?P<food_type_id>\d+)/$', views.food_type_delete, name='food_type_delete'),
    re_path(r'^menu/add/$', views.menu_add, name='menu_add'),
    re_path(r'^menu/for-staff/$', views.menu_for_staff, name='menu_for_staff'),
    re_path(r'menu_by_em', views.get_menu_by_emotion, name='menu_by_em'),
    re_path(r'menu_like', views.menu_like, name='menu_like'),
    re_path(r'menu_dislike', views.menu_dislike, name='menu_dislike'),
    re_path(r'menu_review_recommendation', views.menu_review_recommendation, name='menu_review_recommendation'),
    re_path(r'^menu/$', views.main_list, name='menu'),
    re_path(r'^$', views.main_list, name='menu'),
    re_path(r'^user/(?P<username>[a-zA-Z0-9._]*)/$', views.user_profile, name='user_profile'),
    re_path(r'^user/(?P<username>[a-zA-Z0-9._]*)/editing/$', views.user_profile_editing, name='user_profile_editing'),
    re_path(r'^logout/', views.logout, name='logout'),
]

reservation/urls.py
from django.urls import re_path

from reservation import views

urlpatterns = [
    re_path(r'show_reservation', views.show_reservation, name='show_reservation'),
    re_path(r'delete_reservation', views.delete_reservation, name='delete_reservation'),
    re_path(r'reserve_table', views.reserve_table, name='reserve_table'),
    re_path(r'^add-table/$', views.reservation_add_table, name='reservation_add_table'),
    re_path(r'^table/change/(?P<table_id>\d+)/$', views.reservation_change_table, name='reservation_change_table'),
    re_path(r'^delete-table/(?P<table_id>\d+)/$', views.reservation_delete_table, name='reservation_delete_table'),
    re_path(r'^$', views.main_list, name='reservation'),
]

recSys/models.py
from django.contrib.auth.models import AbstractUser
from django.core.validators import MaxValueValidator
from django.db import models
from django.urls import reverse

from nestolovaya_itmo.s3_storage import CustomStorage


class Menu(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=100, verbose_name='Название')
    composition = models.TextField(max_length=2047, verbose_name='Состав')
    weight = models.CharField(default=0, max_length=100, verbose_name='Вес')
    price = models.SmallIntegerField(default=0, verbose_name='Цена')

    FOOD_TYPE = (
        ('FO', 'Блюда'),
        ('DR', 'Напитки'),
        ('DE', 'Десерты'),
        ('CO', 'Комбо')
    )

    food_type = models.CharField(max_length=2, choices=FOOD_TYPE, help_text='Тип еды', verbose_name='Тип еды')
    food_type_detail = models.ForeignKey('FoodTypeDetail', null=True, on_delete=models.SET_NULL, verbose_name='Тип еды подробнее')
    image = models.ImageField(max_length=300, upload_to='menu/', storage=CustomStorage, verbose_name='Картинка')
    likes = models.IntegerField(default=0, verbose_name='Лайки')
    dislikes = models.IntegerField(default=0, verbose_name='Дизлайки')
    views = models.BigIntegerField(default=0, verbose_name='Просмотры')
    final_coefficient = models.SmallIntegerField(default=0, verbose_name='Итоговый коэффициент')
    available = models.BooleanField(default=True, verbose_name='Продается в данный момент')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Меню'
        verbose_name_plural = 'Меню'
        db_table = 'menu'


class FoodTypeDetail(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=30, verbose_name='Тип еды подробнее')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Тип еды подробнее'
        verbose_name_plural = 'Тип еды подробнее'
        db_table = 'food_type'


class TimeCoefficient(models.Model):
    id = models.AutoField(primary_key=True)
    menu = models.ForeignKey('Menu', null=True, on_delete=models.CASCADE, verbose_name='Блюдо, напиток и т.д. из меню')
    month = models.SmallIntegerField(verbose_name='Месяц, в который работает коэффициент')
    hour = models.SmallIntegerField(verbose_name='Час, в который работает коэффициент')
    coefficient = models.IntegerField(default=0, verbose_name='Коэффициент по времени')

    def __str__(self):
        return '%s, month: %s, hour: %s, coefficient: %s' % (self.menu.title, self.month, self.hour, self.coefficient)

    class Meta:
        verbose_name = 'Коэффициент время'
        verbose_name_plural = 'Коэффициенты время'
        db_table = 'time_coefficient'


class EmotionCoefficient(models.Model):
    id = models.AutoField(primary_key=True)
    menu = models.ForeignKey('Menu', null=True, on_delete=models.CASCADE, verbose_name='Блюдо, напиток и т.д. из меню')

    EMOTION_TYPE = (
        ('HA', 'happy'),
        ('NE', 'neutral'),
        ('SA', 'sad'),
        ('AN', 'angry')
    )

    emotion = models.CharField(max_length=2, choices=EMOTION_TYPE, verbose_name='Эмоция')
    coefficient = models.IntegerField(default=0, verbose_name='Коэффициент по эмоции')

    def __str__(self):
        return '%s, emotion: %s, coefficient: %s' % (self.menu.title, self.emotion, self.coefficient)

    class Meta:
        verbose_name = 'Коэффициент настроения'
        verbose_name_plural = 'Коэффициенты настроения'
        db_table = 'emotion_coefficient'


class MenuReview(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey('User', null=False, on_delete=models.CASCADE, verbose_name='user id')
    menu = models.ForeignKey('Menu', null=False, on_delete=models.CASCADE, verbose_name='menu_id')
    review = models.BooleanField(null=True, verbose_name='like или dislike')

    def __str__(self):
        return 'user_id: %s, menu_id: %s, review: %s' % (self.user_id, self.menu_id, self.review)

    class Meta:
        verbose_name = 'Лайк или дизлайк'
        verbose_name_plural = 'Лайк или дизлайк'
        db_table = 'menu_review'


class User(AbstractUser):
    university_id = models.PositiveIntegerField(default=000000, verbose_name='University_id')

    def __str__(self):
        return self.username

reservation/models.py
from datetime import date
from django.utils import timezone

from nestolovaya_itmo.s3_storage import CustomStorage
from recSys.models import User
from django.db import models


class Table(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=100, verbose_name='Название')
    image = models.ImageField(max_length=300, upload_to='tables/', storage=CustomStorage, verbose_name='Картинка')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Стол'
        verbose_name_plural = 'Столы'
        db_table = 'table'


class Reservation(models.Model):
    id = models.AutoField(primary_key=True)
    date_of_creation = models.DateField(default=date.today, verbose_name='Дата создания бронирования')
    date_of_reservation = models.DateField(default=date.today, verbose_name='Дата бронирования')
    time_of_reservation = models.TimeField(default=timezone.now, verbose_name='Время бронирования')
    user = models.ForeignKey('recSys.User', null=False, on_delete=models.CASCADE)
    table = models.ForeignKey('Table', null=False, on_delete=models.CASCADE)

    def __str__(self):
        return 'table: %s, user: %s %s, time: %s' % (self.table.title, self.user.first_name, self.user.last_name, self.date_of_reservation)

    class Meta:
        verbose_name = 'Бронирование'
        verbose_name_plural = 'Бронирования'
        db_table = 'reservation'

reservation/forms.py
from django import forms

from reservation.models import Table


class TableCreationForm(forms.ModelForm):

    class Meta:
        model = Table
        fields = '__all__'


class TableChangeForm(forms.ModelForm):

    class Meta:
        model = Table
        fields = '__all__'

reservation/views.py
import datetime
import re

from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render, get_object_or_404

from reservation.forms import TableCreationForm, TableChangeForm
from reservation.models import Reservation, Table


def show_reservation(request):
    table_id = request.GET.get('table_id')
    date = request.GET.get('date')
    queryset = list(Reservation.objects.filter(table_id=table_id, date_of_reservation=date)
                    .order_by('time_of_reservation')
                    .values('user_id', 'user__first_name', 'user__university_id', 'time_of_reservation', 'user__username'))
    print(queryset)
    response = {
        'table_date_show': queryset,
    }

    return JsonResponse(response)


def delete_reservation(request):
    true_user_id = request.user.id
    sus_user_id = request.GET.get('user_id')

    # if user staff
    if request.user.is_staff:
        user_id = sus_user_id
    else:
        user_id = true_user_id

    if request.user.is_authenticated:
        table_id = request.GET.get('table_id')
        date_of_reservation = request.GET.get('date_of_reservation')
        time_of_reservation = request.GET.get('time_of_reservation')
        Reservation.objects.filter(user_id=user_id, table_id=table_id, date_of_reservation=date_of_reservation,
                                   time_of_reservation=time_of_reservation).delete()
        return JsonResponse({'status': 'success'}, status=200)

    return JsonResponse({'errors': 'Что-то пошло не так, скорее всего вы не авторизованы'}, status=400)


def reserve_table(request):
    if request.method == "POST" and request.user.is_authenticated:
        user_id = request.user.id
        table_id = request.POST.get('table_id')
        date_of_reservation = request.POST.get('date_of_reservation')
        time_of_reservation = request.POST.get('time_of_reservation')

        # delete old reservations
        date_now = datetime.datetime.now().date()
        Reservation.objects.filter(date_of_reservation__lt=date_now).delete()

        # check that there are 1 reservation per table
        how_many_reservations_per_table = Reservation.objects.filter(user_id=user_id, table_id=table_id,
                                                                     date_of_reservation=date_of_reservation).count()
        if how_many_reservations_per_table >= 1 and not request.user.is_staff:
            return JsonResponse({'errors': f'У вас уже есть бронированиe на этот стол, {date_of_reservation}'},
                                status=400)

        # check time, hours from 10 to 17, minutes 00 or 30
        time_is_correct = re.fullmatch(r'^1[0-7]:[03]0$', time_of_reservation)
        if not time_is_correct:
            return JsonResponse({'errors': 'Неправильное время'}, status=400)

        # check is table reserved
        table_is_reserved = Reservation.objects.filter(table_id=table_id, date_of_reservation=date_of_reservation,
                                                       time_of_reservation=time_of_reservation).exists()
        if table_is_reserved:
            return JsonResponse({'errors': 'Это время занято'}, status=400)

        if not table_is_reserved:
            Reservation.objects.create(user_id=user_id, table_id=table_id, date_of_reservation=date_of_reservation,
                                       time_of_reservation=time_of_reservation)
            return JsonResponse({'status': 'success'}, status=200)

    return JsonResponse({'errors': 'Что-то пошло не так, скорее всего вы не авторизованы'}, status=400)


def reservation_add_table(request):
    if request.user.is_staff and request.method == 'GET':
        context = {

        }

        return render(request, 'reservation_add_table.html', context)

    if request.user.is_staff and request.method == 'POST':
        form = TableCreationForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            context = {
                'status': 'success',
                'response_message': 'Успешно добавлено'
            }

            return render(request, 'reservation_add_table.html', context)
        else:
            context = {
                'status': 'warning',
                'response_message': 'Не удалось добавить',
            }

            return render(request, 'reservation_add_table.html', context)

    return HttpResponseRedirect('/')


def reservation_change_table(request, table_id):
    instance = get_object_or_404(Table, id=table_id)

    if request.user.is_staff and request.method == 'GET':
        context = {
            'instance': instance,
        }

        return render(request, 'reservation_update_table.html', context)

    if request.user.is_staff and request.method == 'POST':
        form = TableChangeForm(request.POST, request.FILES, instance=instance)
        if form.is_valid():
            if request.FILES:
                Table.objects.get(id=table_id).image.delete()
                form.save()
            else:
                form.save()

            return HttpResponseRedirect(f'/reservation/')
        else:
            context = {
                'instance': instance,
                'status': 'warning',
                'response_message': 'Не удалось изменить',
            }

            return render(request, 'reservation_update_table.html', context)

    return HttpResponseRedirect('/')


def reservation_delete_table(request, table_id):
    if request.user.is_staff and Table.objects.filter(id=table_id).exists():
        Table.objects.get(id=table_id).image.delete()
        Table.objects.filter(id=table_id).delete()

    return HttpResponseRedirect('/reservation/')


def main_list(request):
    queryset = Table.objects.order_by('id')

    context = {
        'queryset': queryset,
    }
    return render(request, 'reservation.html', context)

resources/templates/food_type.html
{% extends "parts/commonPart.html" %}
{% block head_title %}Добавить в меню{% endblock %}
{% block content %}
    <div class="container">

        <h3 class="mb-4">Добавить/изменить/удалить тип еды</h3>

        {% if status %}
            <div class="alert alert-{{ status }}" role="alert">
            {{ response_message }}
            </div>
        {% endif %}

        <form method="POST"> {% csrf_token %}
            <div class="mb-3">
                <label for="food-type-detail" class="form-label">Тип еды</label>
                <input type="text" class="form-control" id="food-type-detail"
                       placeholder="" name="title" required>
            </div>
            <button class="btn btn-success mb-3" type="submit">Добавить</button>
        </form>

        <div class="input-group mb-3">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Тип еды</th>
                        <th scope="col">Действие</th>
                    </tr>
                </thead>
                <tbody>
                    {% for ft in instance %}
                        <tr>
                            <td>{{ ft.title }}</td>
                            <td>
                                <a class="btn btn-outline-primary" href="/menu/food-type/update/{{ ft.id }}/">Изменить</a>
                                <a class="btn btn-outline-danger" href="/menu/food-type/delete/{{ ft.id }}/">Удалить</a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

resources/templates/food_type_update.html
{% extends "parts/commonPart.html" %}
{% block head_title %}Изменить тип продукта{% endblock %}
{% block content %}
    <div class="container">

        {% if status %}
            <div class="alert alert-{{ status }}" role="alert">
            {{ response_message }}
            </div>
        {% endif %}

        <h3 class="mb-4">Изменить тип еды</h3>

        <form method="POST"> {% csrf_token %}
            <div class="mb-3">
                <label for="food-type-detail" class="form-label">Тип еды</label>
                <input type="text" class="form-control" id="food-type-detail"
                       placeholder="{{ instance }}" name="title" required>
            </div>
            <button class="btn btn-success" type="submit">Изменить</button>
            <a class="btn btn-secondary" href="/menu/food-type/">К списку</a>
        </form>


    </div>
{% endblock %}

resources/templates/menu_add.html
{% extends "parts/commonPart.html" %}
{% block head_title %}Добавить в меню{% endblock %}
{% block content %}
    <div class="container">

        {% if status %}
            <div class="alert alert-{{ status }}" role="alert">
            {{ response_message }}
            </div>
        {% endif %}

        <h3 class="mb-4">Добавить в меню</h3>
        <form method="POST" enctype="multipart/form-data"> {% csrf_token %}
            <div class="input-group mb-3">
                <label class="input-group-text" for="food-type">Тип еды</label>
                <select class="form-select" id="food-type" name="food_type" required="">
                    <option selected="" disabled="" value="">Выберите...</option>
                    {% for ft in food_type %}
                        <option value="{{ ft.0 }}">{{ ft.1 }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="mb-1">
                <a class="" href="/menu/food-type/">Добавить/изменить/удалить тип еды подробнее</a>
            </div>
            <div class="input-group mb-3">
                <label class="input-group-text" for="food-type-detail">Тип еды подробнее</label>
                <select class="form-select" id="food-type-detail" name="food_type_detail" required="">
                    <option selected="" disabled="" value="">Выберите...</option>
                    {% for ft in food_type_detail %}
                        <option value="{{ ft.id }}">
                            {{ ft.title }}
                        </option>
                    {% endfor %}
                </select>
            </div>
            <div class="mb-3">
                <label for="formGroupExampleInput" class="form-label">Название</label>
                <input type="text" class="form-control" id="formGroupExampleInput"
                       placeholder="" name="title" required>
            </div>
            <div class="form-floating mb-3">
                <textarea class="form-control" placeholder="" id="floatingTextarea2"
                          style="height: 100px" name="composition" required></textarea>
                <label for="floatingTextarea2">Состав</label>
            </div>
            <div class="mb-3">
                <label for="formGroupExampleInput" class="form-label">Стоимость</label>
                <input type="number" class="form-control" id="formGroupExampleInput"
                       placeholder="" name="price" required>
            </div>
            <div class="mb-3">
                <label for="id_image" class="form-label">Картинка</label>
                <input type="file" class="form-control" id="id_image"
                       name="image" accept="image/jpeg" required>
            </div>
            <div class="mb-3">
                <label for="formGroupExampleInput" class="form-label">Вес</label>
                <input type="text" class="form-control" id="formGroupExampleInput"
                       placeholder="Писать вместе с гр или мл" name="weight" required>
            </div>
            <div class="mb-3">
                <label for="available" class="form-check-label">Продается в данный момент:</label>
                <input type="checkbox" class="form-check-input" name="available" id="available" checked>
            </div>
            <button class="btn btn-success" type="submit">Опубликовать</button>
        </form>

    </div>
{% endblock %}

resources/templates/menu_detail.html
{% extends "parts/commonPart.html" %}
{% load static %}
{% block head_title %}{{ instance.title }}{% endblock %}
{% block content %}
    <div class="container">
        <div class="menu-detail-card">
            <div class="card-header">
                <h5 class="mb-0">{{ instance.title }}</h5>
            </div>
            <div class="card-body">
                <blockquote class="blockquote mb-0">
                    <img src="{{ instance.image.url }}" class="card-img-top" alt="{{ instance.title }}">
                    <p class="menu-detail-composition-header">Состав:</p>
                    <p class="menu-detail-composition" style="white-space: pre-line">{{ instance.composition }}</p>
                    <p class="menu-detail-price">Цена: {{ instance.price }} р</p>
                    <p class="menu-detail-weight">Вес/объём: {{ instance.weight }}</p>
                    <div class="container-review">
                        <svg class="heart-outline heart-color" xmlns="http://www.w3.org/2000/svg"
                             viewBox="0 0 24 24" style="width: 48px; height: 48px;" id="like">
                            <path fill="currentColor"></path>
                        </svg>
                        <svg class="heart-broken-outline heart-color" xmlns="http://www.w3.org/2000/svg"
                             viewBox="0 0 24 24" style="width: 48px; height: 48px;" id="dislike">
                            <path fill="currentColor"></path>
                        </svg>
                    </div>
                </blockquote>
                {% if user.is_staff %}
                    <br>
                    <a href="/menu/update/{{ instance.id }}/" class="btn btn-dark" type="submit">Редактировать</a>

                    <!-- Button trigger modal -->
                    <button type="button" class="btn btn-dark" data-bs-toggle="modal" data-bs-target="#deleteMenu">
                    Удалить
                    </button>

                    <!-- Modal -->
                    <div class="modal fade" id="deleteMenu" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title alert alert-warning" id="exampleModalLabel">Внимание</h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body">
                                    <div class="mb-3">
                                            Пожалуйста, не удаляйте единицу меню, т.к. может потеряться важная статистика.
                                    </div>
                                    <div class="mb-3">
                                            Удаляйте только в том случае, если на 100% уверены в том, что единица меню больше никогда использоваться не будет.
                                    </div>
                                    <div class="mb-3">
                                            Вместо удаления измените состояние доступности единицы меню на недоступно, это можно сделать на странице редактирования.
                                    </div>
                                </div>
                                <div class="modal-footer">
                                    <a class="btn btn-secondary" href="/menu/delete/{{ instance.id }}/" type="submit">Удалить</a>
                                    <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Закрыть</button>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}
{% block script %}
    <script src="{% static 'js/review.js' %}"></script>
    <!-- Meta -->
    {{ review|json_script:"review" }}
    {{ instance.id|json_script:"menu_id" }}
    {{ request.user.is_authenticated|json_script:"user_auth" }}
{% endblock %}

resources/templates/menu_update.html
{% extends "parts/commonPart.html" %}
{% block head_title %}Редактирование {{ instance.title|lower }}{% endblock %}
{% block content %}
    <div class="container">
        {% if status %}
            <div class="alert alert-{{ status }}" role="alert">
            {{ response_message }}
            </div>
        {% endif %}
        <h3 class="mb-4">Редактировать</h3>
        <form method="POST" action="" enctype="multipart/form-data"> {% csrf_token %}
            <div class="mb-3">
                <label for="formGroupExampleInput" class="form-label">Название</label>
                <input type="text" class="form-control" id="formGroupExampleInput"
                       placeholder="" name="title"
                       value="{{ instance.title }}">
            </div>
            <div class="form-floating mb-3">
                <textarea class="form-control" placeholder="" id="floatingTextarea"
                          style="height: 100px" name="composition">{{ instance.composition }}</textarea>
                <label for="floatingTextarea">Состав</label>
            </div>
            <div class="input-group mb-3">
                <label class="input-group-text" for="food-type">Тип еды</label>
                <select class="form-select" id="food-type" name="food_type" required="">
                    <option selected="" disabled="" value="">{{ instance.get_food_type_display }}</option>
                    {% for ft in food_type %}
                        <option value="{{ ft.0 }}">{{ ft.1 }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="mb-1">
                <a class="" href="/menu/food-type/">Добавить/изменить/удалить тип еды подробнее</a>
            </div>
            <div class="input-group mb-3">
                <label class="input-group-text" for="food-type-detail">Тип еды подробнее</label>
                <select class="form-select" id="food-type-detail" name="food_type_detail" required="">
                    <option selected="" disabled="" value="">{{ instance.food_type_detail }}</option>
                    {% for ft in food_type_detail %}
                        <option value="{{ ft.id }}">{{ ft.title }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="mb-3">
                <label for="id_image" class="form-label">Картинка</label>
                <input type="file" class="form-control" id="id_image"
                       name="image" accept="image/jpeg" value="{{ instance.image }}" >
            </div>
            <div class="mb-3">
                <label for="formGroupExampleInput" class="form-label">Стоимость</label>
                <input type="number" class="form-control" id="formGroupExampleInput"
                       placeholder="" name="price"
                       value="{{ instance.price }}">
            </div>
            <div class="mb-3">
                <label for="formGroupExampleInput" class="form-label">Вес</label>
                <input type="text" class="form-control" id="formGroupExampleInput"
                       placeholder="Писать вместе с гр или мл" name="weight"
                       value="{{ instance.weight }}">
            </div>
            <div class="mb-3">
                <label for="available" class="form-check-label">Продается в данный момент:</label>
                <input type="checkbox" class="form-check-input" name="available" id="available"
                       {% if instance.available %} checked {% endif %}>
            </div>
            <input class="btn btn-dark" type="submit" value="Изменить" name="">
        </form>
    </div>
{% endblock %}

resources/templates/reservation_add_table.html
{% extends "parts/commonPart.html" %}
{% block head_title %}Добавить столик{% endblock %}
{% block content %}
    <div class="container">
        {% if status %}
            <div class="alert alert-{{ status }}" role="alert">
            {{ response_message }}
            </div>
        {% endif %}
        <h3 class="mb-4">Добавить столик</h3>
        <form method="POST" enctype="multipart/form-data"> {% csrf_token %}
            <div class="mb-3">
                <label for="formGroupExampleInput" class="form-label">Название</label>
                <input type="text" class="form-control" id="formGroupExampleInput"
                       placeholder="" name="title" required>
            </div>
            <div class="mb-3">
                <label for="id_image" class="form-label">Картинка</label>
                <input type="file" class="form-control" id="id_image"
                       name="image" accept="image/jpeg" required>
            </div>
            <button class="btn btn-success" type="submit">Опубликовать</button>
        </form>
    </div>
{% endblock %}

resources/templates/reservation_update_table.html
{% extends "parts/commonPart.html" %}
{% block head_title %}Изменить столик{% endblock %}
{% block content %}
    <div class="container">
        {% if status %}
            <div class="alert alert-{{ status }}" role="alert">
            {{ response_message }}
            </div>
        {% endif %}
        <h3 class="mb-4">Изменить столик</h3>
        <form method="POST" enctype="multipart/form-data"> {% csrf_token %}
            <div class="mb-3">
                <label for="tableTitle" class="form-label">Название</label>
                <input type="text" class="form-control" id="tableTitle"
                       value="{{ instance.title }}" placeholder="" name="title">
            </div>
            <div class="mb-3">
                <label for="id_image" class="form-label">Картинка</label>
                <input type="file" class="form-control" id="id_image"
                       name="image" accept="image/jpeg">
            </div>
            <button class="btn btn-success" type="submit">Изменить</button>
        </form>
    </div>
{% endblock %}